"""Add Review Model

Revision ID: 0cc43cdbe444
Revises: 6ef132cdaa6b
Create Date: 2023-07-12 08:29:47.273394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc43cdbe444'
down_revision = '6ef132cdaa6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
