"""Create Game Model

Revision ID: 6ef132cdaa6b
Revises: 886a16b4664b
Create Date: 2023-07-12 08:27:06.214738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef132cdaa6b'
down_revision = '886a16b4664b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
