"""Add Review Model

Revision ID: 886a16b4664b
Revises: 563e14e8849b
Create Date: 2023-07-11 11:59:26.023719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886a16b4664b'
down_revision = '563e14e8849b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
